version: '3'

services:
  bitcoin-trend-bot:
    build: .
    container_name: bitcoin-trend-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    command: python run.py trade --timeframe 1h --interval 300